export const placeholderValues = [
    "Mens casual slim fit",
    "Mens cotton jacket",
    "Womens T-shirt",
    "Rain jacket",
    "Short sleeve moisture",
    "Curved gaming monitor",
    "Portable external hard drive",
    "Chain bracelet",
    "Type here to find products",
    "Search by keyword",
    "Looking for something specific?",
    "What are you looking for today?",
    "Find products or categories",
    "Search for deals and discounts",
    "Search for your favorite items",
    "Find your perfect item",
    "What's on your mind?",
    "Browse our selection",
    "Discover new arrivals",
    "Unleash your shopping desires",
    "Start your search here",
    "Explore our catalog",
    "Looking for inspiration?",
    "Search for top brands",
    "Find the best deals",
    "Shop by category",
    "New styles are here",
    "Ready to shop?",
    "Discover your style",
    "Search for inspiration",
    "What are you craving?",
    "Find must-have items",
]
